services:
  netmon:
    image: jonfairbanks/netmon
    restart: always
    environment:
      - DEVICE=MyDevice
      - INFLUX_TOKEN=abcdef123==
      - INFLUX_ORG=MyInfluxOrg
      - INFLUX_BUCKET=MyInfluxBucket
      - PLUG=1.2.3.4
    volumes:
      - /sys/:/sys/:ro
